# Generated by Django 5.2 on 2025-05-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
